/*
Responses with various schema formats

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schema-object

API version: 1.0
Contact: a-team@goarmy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package complex_nesting

import (
	"encoding/json"
)

// checks if the ArrayOfObjectsOfObjectsAndArrays type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArrayOfObjectsOfObjectsAndArrays{}

// ArrayOfObjectsOfObjectsAndArrays Array of objects (containing objects and arrays)
type ArrayOfObjectsOfObjectsAndArrays struct {
}

// NewArrayOfObjectsOfObjectsAndArrays instantiates a new ArrayOfObjectsOfObjectsAndArrays object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArrayOfObjectsOfObjectsAndArrays() *ArrayOfObjectsOfObjectsAndArrays {
	this := ArrayOfObjectsOfObjectsAndArrays{}
	return &this
}

// NewArrayOfObjectsOfObjectsAndArraysWithDefaults instantiates a new ArrayOfObjectsOfObjectsAndArrays object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArrayOfObjectsOfObjectsAndArraysWithDefaults() *ArrayOfObjectsOfObjectsAndArrays {
	this := ArrayOfObjectsOfObjectsAndArrays{}
	return &this
}

func (o ArrayOfObjectsOfObjectsAndArrays) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArrayOfObjectsOfObjectsAndArrays) ToMap() (map[string]interface{}, error) {
	toSerialize := make([]interface{}, len(o.Items))
	for i, item := range o.Items {
		toSerialize[i] = item
	}
	return toSerialize, nil
}

func (o *ArrayOfObjectsOfObjectsAndArrays) UnmarshalJSON(data []byte) (err error) {
	return json.Unmarshal(data, &o.Items)
}

type NullableArrayOfObjectsOfObjectsAndArrays struct {
	value ArrayOfObjectsOfObjectsAndArrays
	isSet bool
}

func (v NullableArrayOfObjectsOfObjectsAndArrays) Get() ArrayOfObjectsOfObjectsAndArrays {
	return v.value
}

func (v *NullableArrayOfObjectsOfObjectsAndArrays) Set(val ArrayOfObjectsOfObjectsAndArrays) {
	v.value = val
	v.isSet = true
}

func (v NullableArrayOfObjectsOfObjectsAndArrays) IsSet() bool {
	return v.isSet
}

func (v *NullableArrayOfObjectsOfObjectsAndArrays) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArrayOfObjectsOfObjectsAndArrays(val ArrayOfObjectsOfObjectsAndArrays) *NullableArrayOfObjectsOfObjectsAndArrays {
	return &NullableArrayOfObjectsOfObjectsAndArrays{value: val, isSet: true}
}

func (v NullableArrayOfObjectsOfObjectsAndArrays) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArrayOfObjectsOfObjectsAndArrays) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


