/*
Responses with various schema formats

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schema-object

API version: 1.0
Contact: a-team@goarmy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package complex_nesting

import (
	"encoding/json"
)

// checks if the ObjectOfAdditionalPropertiesObjectPolymorphismValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectOfAdditionalPropertiesObjectPolymorphismValue{}

// ObjectOfAdditionalPropertiesObjectPolymorphismValue struct for ObjectOfAdditionalPropertiesObjectPolymorphismValue
type ObjectOfAdditionalPropertiesObjectPolymorphismValue struct {
	Primitive *string `json:"primitive,omitempty"`
	Boolean *bool `json:"boolean,omitempty"`
	Metadata NullableObjectOfAdditionalPropertiesObjectPolymorphismValueMetadata `json:"metadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ObjectOfAdditionalPropertiesObjectPolymorphismValue ObjectOfAdditionalPropertiesObjectPolymorphismValue

// NewObjectOfAdditionalPropertiesObjectPolymorphismValue instantiates a new ObjectOfAdditionalPropertiesObjectPolymorphismValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectOfAdditionalPropertiesObjectPolymorphismValue() *ObjectOfAdditionalPropertiesObjectPolymorphismValue {
	this := ObjectOfAdditionalPropertiesObjectPolymorphismValue{}
	return &this
}

// NewObjectOfAdditionalPropertiesObjectPolymorphismValueWithDefaults instantiates a new ObjectOfAdditionalPropertiesObjectPolymorphismValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectOfAdditionalPropertiesObjectPolymorphismValueWithDefaults() *ObjectOfAdditionalPropertiesObjectPolymorphismValue {
	this := ObjectOfAdditionalPropertiesObjectPolymorphismValue{}
	return &this
}

// GetPrimitive returns the Primitive field value if set, zero value otherwise.
func (o *ObjectOfAdditionalPropertiesObjectPolymorphismValue) GetPrimitive() string {
	if o == nil || IsNil(o.Primitive) {
		var ret string
		return ret
	}
	return *o.Primitive
}

// GetPrimitiveOk returns a tuple with the Primitive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectOfAdditionalPropertiesObjectPolymorphismValue) GetPrimitiveOk() (*string, bool) {
	if o == nil || IsNil(o.Primitive) {
		return nil, false
	}
	return o.Primitive, true
}

// HasPrimitive returns a boolean if a field has been set.
func (o *ObjectOfAdditionalPropertiesObjectPolymorphismValue) HasPrimitive() bool {
	if o != nil && !IsNil(o.Primitive) {
		return true
	}

	return false
}

// SetPrimitive gets a reference to the given string and assigns it to the Primitive field.
func (o *ObjectOfAdditionalPropertiesObjectPolymorphismValue) SetPrimitive(v string) {
	o.Primitive = &v
}

// GetBoolean returns the Boolean field value if set, zero value otherwise.
func (o *ObjectOfAdditionalPropertiesObjectPolymorphismValue) GetBoolean() bool {
	if o == nil || IsNil(o.Boolean) {
		var ret bool
		return ret
	}
	return *o.Boolean
}

// GetBooleanOk returns a tuple with the Boolean field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectOfAdditionalPropertiesObjectPolymorphismValue) GetBooleanOk() (*bool, bool) {
	if o == nil || IsNil(o.Boolean) {
		return nil, false
	}
	return o.Boolean, true
}

// HasBoolean returns a boolean if a field has been set.
func (o *ObjectOfAdditionalPropertiesObjectPolymorphismValue) HasBoolean() bool {
	if o != nil && !IsNil(o.Boolean) {
		return true
	}

	return false
}

// SetBoolean gets a reference to the given bool and assigns it to the Boolean field.
func (o *ObjectOfAdditionalPropertiesObjectPolymorphismValue) SetBoolean(v bool) {
	o.Boolean = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ObjectOfAdditionalPropertiesObjectPolymorphismValue) GetMetadata() ObjectOfAdditionalPropertiesObjectPolymorphismValueMetadata {
	if o == nil || IsNil(o.Metadata.Get()) {
		var ret ObjectOfAdditionalPropertiesObjectPolymorphismValueMetadata
		return ret
	}
	return *o.Metadata.Get()
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ObjectOfAdditionalPropertiesObjectPolymorphismValue) GetMetadataOk() (*ObjectOfAdditionalPropertiesObjectPolymorphismValueMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return o.Metadata.Get(), o.Metadata.IsSet()
}

// HasMetadata returns a boolean if a field has been set.
func (o *ObjectOfAdditionalPropertiesObjectPolymorphismValue) HasMetadata() bool {
	if o != nil && o.Metadata.IsSet() {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given NullableObjectOfAdditionalPropertiesObjectPolymorphismValueMetadata and assigns it to the Metadata field.
func (o *ObjectOfAdditionalPropertiesObjectPolymorphismValue) SetMetadata(v ObjectOfAdditionalPropertiesObjectPolymorphismValueMetadata) {
	o.Metadata.Set(&v)
}
// SetMetadataNil sets the value for Metadata to be an explicit nil
func (o *ObjectOfAdditionalPropertiesObjectPolymorphismValue) SetMetadataNil() {
	o.Metadata.Set(nil)
}

// UnsetMetadata ensures that no value is present for Metadata, not even an explicit nil
func (o *ObjectOfAdditionalPropertiesObjectPolymorphismValue) UnsetMetadata() {
	o.Metadata.Unset()
}

func (o ObjectOfAdditionalPropertiesObjectPolymorphismValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectOfAdditionalPropertiesObjectPolymorphismValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Primitive) {
		toSerialize["primitive"] = o.Primitive
	}
	if !IsNil(o.Boolean) {
		toSerialize["boolean"] = o.Boolean
	}
	if o.Metadata.IsSet() {
		toSerialize["metadata"] = o.Metadata.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ObjectOfAdditionalPropertiesObjectPolymorphismValue) UnmarshalJSON(data []byte) (err error) {
	varObjectOfAdditionalPropertiesObjectPolymorphismValue := _ObjectOfAdditionalPropertiesObjectPolymorphismValue{}

	err = json.Unmarshal(data, &varObjectOfAdditionalPropertiesObjectPolymorphismValue)

	if err != nil {
		return err
	}

	*o = ObjectOfAdditionalPropertiesObjectPolymorphismValue(varObjectOfAdditionalPropertiesObjectPolymorphismValue)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "primitive")
		delete(additionalProperties, "boolean")
		delete(additionalProperties, "metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableObjectOfAdditionalPropertiesObjectPolymorphismValue struct {
	value *ObjectOfAdditionalPropertiesObjectPolymorphismValue
	isSet bool
}

func (v NullableObjectOfAdditionalPropertiesObjectPolymorphismValue) Get() *ObjectOfAdditionalPropertiesObjectPolymorphismValue {
	return v.value
}

func (v *NullableObjectOfAdditionalPropertiesObjectPolymorphismValue) Set(val *ObjectOfAdditionalPropertiesObjectPolymorphismValue) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectOfAdditionalPropertiesObjectPolymorphismValue) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectOfAdditionalPropertiesObjectPolymorphismValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectOfAdditionalPropertiesObjectPolymorphismValue(val *ObjectOfAdditionalPropertiesObjectPolymorphismValue) *NullableObjectOfAdditionalPropertiesObjectPolymorphismValue {
	return &NullableObjectOfAdditionalPropertiesObjectPolymorphismValue{value: val, isSet: true}
}

func (v NullableObjectOfAdditionalPropertiesObjectPolymorphismValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectOfAdditionalPropertiesObjectPolymorphismValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


