/*
Callback Example

API definition with callback

API version: 1.0.0
Contact: a-team@goarmy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package callbacks

import (
	"encoding/json"
)

// checks if the StreamsPost204Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StreamsPost204Response{}

// StreamsPost204Response struct for StreamsPost204Response
type StreamsPost204Response struct {
	Email *string `json:"email,omitempty"`
	Name *string `json:"name,omitempty"`
	Id *int64 `json:"id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _StreamsPost204Response StreamsPost204Response

// NewStreamsPost204Response instantiates a new StreamsPost204Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamsPost204Response() *StreamsPost204Response {
	this := StreamsPost204Response{}
	return &this
}

// NewStreamsPost204ResponseWithDefaults instantiates a new StreamsPost204Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamsPost204ResponseWithDefaults() *StreamsPost204Response {
	this := StreamsPost204Response{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *StreamsPost204Response) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamsPost204Response) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *StreamsPost204Response) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *StreamsPost204Response) SetEmail(v string) {
	o.Email = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *StreamsPost204Response) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamsPost204Response) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *StreamsPost204Response) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *StreamsPost204Response) SetName(v string) {
	o.Name = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *StreamsPost204Response) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamsPost204Response) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *StreamsPost204Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *StreamsPost204Response) SetId(v int64) {
	o.Id = &v
}

func (o StreamsPost204Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StreamsPost204Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StreamsPost204Response) UnmarshalJSON(data []byte) (err error) {
	varStreamsPost204Response := _StreamsPost204Response{}

	err = json.Unmarshal(data, &varStreamsPost204Response)

	if err != nil {
		return err
	}

	*o = StreamsPost204Response(varStreamsPost204Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "email")
		delete(additionalProperties, "name")
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStreamsPost204Response struct {
	value *StreamsPost204Response
	isSet bool
}

func (v NullableStreamsPost204Response) Get() *StreamsPost204Response {
	return v.value
}

func (v *NullableStreamsPost204Response) Set(val *StreamsPost204Response) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamsPost204Response) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamsPost204Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamsPost204Response(val *StreamsPost204Response) *NullableStreamsPost204Response {
	return &NullableStreamsPost204Response{value: val, isSet: true}
}

func (v NullableStreamsPost204Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStreamsPost204Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


