/*
Polymorphism support

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schema-object

API version: 1.0.0
Contact: a-team@goarmy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polymorphism

import (
	"encoding/json"
)

// checks if the Object1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Object1{}

// Object1 struct for Object1
type Object1 struct {
	A *string `json:"a,omitempty"`
	B *string `json:"b,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Object1 Object1

// NewObject1 instantiates a new Object1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObject1() *Object1 {
	this := Object1{}
	return &this
}

// NewObject1WithDefaults instantiates a new Object1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObject1WithDefaults() *Object1 {
	this := Object1{}
	return &this
}

// GetA returns the A field value if set, zero value otherwise.
func (o *Object1) GetA() string {
	if o == nil || IsNil(o.A) {
		var ret string
		return ret
	}
	return *o.A
}

// GetAOk returns a tuple with the A field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Object1) GetAOk() (*string, bool) {
	if o == nil || IsNil(o.A) {
		return nil, false
	}
	return o.A, true
}

// HasA returns a boolean if a field has been set.
func (o *Object1) HasA() bool {
	if o != nil && !IsNil(o.A) {
		return true
	}

	return false
}

// SetA gets a reference to the given string and assigns it to the A field.
func (o *Object1) SetA(v string) {
	o.A = &v
}

// GetB returns the B field value if set, zero value otherwise.
func (o *Object1) GetB() string {
	if o == nil || IsNil(o.B) {
		var ret string
		return ret
	}
	return *o.B
}

// GetBOk returns a tuple with the B field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Object1) GetBOk() (*string, bool) {
	if o == nil || IsNil(o.B) {
		return nil, false
	}
	return o.B, true
}

// HasB returns a boolean if a field has been set.
func (o *Object1) HasB() bool {
	if o != nil && !IsNil(o.B) {
		return true
	}

	return false
}

// SetB gets a reference to the given string and assigns it to the B field.
func (o *Object1) SetB(v string) {
	o.B = &v
}

func (o Object1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Object1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.A) {
		toSerialize["a"] = o.A
	}
	if !IsNil(o.B) {
		toSerialize["b"] = o.B
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Object1) UnmarshalJSON(data []byte) (err error) {
	varObject1 := _Object1{}

	err = json.Unmarshal(data, &varObject1)

	if err != nil {
		return err
	}

	*o = Object1(varObject1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "a")
		delete(additionalProperties, "b")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableObject1 struct {
	value *Object1
	isSet bool
}

func (v NullableObject1) Get() *Object1 {
	return v.value
}

func (v *NullableObject1) Set(val *Object1) {
	v.value = val
	v.isSet = true
}

func (v NullableObject1) IsSet() bool {
	return v.isSet
}

func (v *NullableObject1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObject1(val *Object1) *NullableObject1 {
	return &NullableObject1{value: val, isSet: true}
}

func (v NullableObject1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObject1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


