/*
Polymorphism support

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schema-object

API version: 1.0.0
Contact: a-team@goarmy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polymorphism

import (
	"encoding/json"
	"fmt"
)

// AnythingOneOfObjectRefRequest - struct for AnythingOneOfObjectRefRequest
type AnythingOneOfObjectRefRequest struct {
	Object1 *Object1
	Object2 *Object2
}

// Object1AsAnythingOneOfObjectRefRequest is a convenience function that returns Object1 wrapped in AnythingOneOfObjectRefRequest
func Object1AsAnythingOneOfObjectRefRequest(v *Object1) AnythingOneOfObjectRefRequest {
	return AnythingOneOfObjectRefRequest{
		Object1: v,
	}
}

// Object2AsAnythingOneOfObjectRefRequest is a convenience function that returns Object2 wrapped in AnythingOneOfObjectRefRequest
func Object2AsAnythingOneOfObjectRefRequest(v *Object2) AnythingOneOfObjectRefRequest {
	return AnythingOneOfObjectRefRequest{
		Object2: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *AnythingOneOfObjectRefRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Object1
	err = newStrictDecoder(data).Decode(&dst.Object1)
	if err == nil {
		jsonObject1, _ := json.Marshal(dst.Object1)
		if string(jsonObject1) == "{}" { // empty struct
			dst.Object1 = nil
		} else {
			match++
		}
	} else {
		dst.Object1 = nil
	}

	// try to unmarshal data into Object2
	err = newStrictDecoder(data).Decode(&dst.Object2)
	if err == nil {
		jsonObject2, _ := json.Marshal(dst.Object2)
		if string(jsonObject2) == "{}" { // empty struct
			dst.Object2 = nil
		} else {
			match++
		}
	} else {
		dst.Object2 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Object1 = nil
		dst.Object2 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(AnythingOneOfObjectRefRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(AnythingOneOfObjectRefRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src AnythingOneOfObjectRefRequest) MarshalJSON() ([]byte, error) {
	if src.Object1 != nil {
		return json.Marshal(&src.Object1)
	}

	if src.Object2 != nil {
		return json.Marshal(&src.Object2)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *AnythingOneOfObjectRefRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Object1 != nil {
		return obj.Object1
	}

	if obj.Object2 != nil {
		return obj.Object2
	}

	// all schemas are nil
	return nil
}

type NullableAnythingOneOfObjectRefRequest struct {
	value *AnythingOneOfObjectRefRequest
	isSet bool
}

func (v NullableAnythingOneOfObjectRefRequest) Get() *AnythingOneOfObjectRefRequest {
	return v.value
}

func (v *NullableAnythingOneOfObjectRefRequest) Set(val *AnythingOneOfObjectRefRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAnythingOneOfObjectRefRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAnythingOneOfObjectRefRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnythingOneOfObjectRefRequest(val *AnythingOneOfObjectRefRequest) *NullableAnythingOneOfObjectRefRequest {
	return &NullableAnythingOneOfObjectRefRequest{value: val, isSet: true}
}

func (v NullableAnythingOneOfObjectRefRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnythingOneOfObjectRefRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


