/*
Polymorphism support

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schema-object

API version: 1.0.0
Contact: a-team@goarmy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polymorphism

import (
	"encoding/json"
	"fmt"
)

// AnythingAnyOfPrimitiveRequest struct for AnythingAnyOfPrimitiveRequest
type AnythingAnyOfPrimitiveRequest struct {
	int32 *int32
	string *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *AnythingAnyOfPrimitiveRequest) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into int32
	err = json.Unmarshal(data, &dst.int32);
	if err == nil {
		jsonint32, _ := json.Marshal(dst.int32)
		if string(jsonint32) == "{}" { // empty struct
			dst.int32 = nil
		} else {
			return nil // data stored in dst.int32, return on the first match
		}
	} else {
		dst.int32 = nil
	}

	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.string);
	if err == nil {
		jsonstring, _ := json.Marshal(dst.string)
		if string(jsonstring) == "{}" { // empty struct
			dst.string = nil
		} else {
			return nil // data stored in dst.string, return on the first match
		}
	} else {
		dst.string = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(AnythingAnyOfPrimitiveRequest)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *AnythingAnyOfPrimitiveRequest) MarshalJSON() ([]byte, error) {
	if src.int32 != nil {
		return json.Marshal(&src.int32)
	}

	if src.string != nil {
		return json.Marshal(&src.string)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableAnythingAnyOfPrimitiveRequest struct {
	value *AnythingAnyOfPrimitiveRequest
	isSet bool
}

func (v NullableAnythingAnyOfPrimitiveRequest) Get() *AnythingAnyOfPrimitiveRequest {
	return v.value
}

func (v *NullableAnythingAnyOfPrimitiveRequest) Set(val *AnythingAnyOfPrimitiveRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAnythingAnyOfPrimitiveRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAnythingAnyOfPrimitiveRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnythingAnyOfPrimitiveRequest(val *AnythingAnyOfPrimitiveRequest) *NullableAnythingAnyOfPrimitiveRequest {
	return &NullableAnythingAnyOfPrimitiveRequest{value: val, isSet: true}
}

func (v NullableAnythingAnyOfPrimitiveRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnythingAnyOfPrimitiveRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


