/*
Polymorphism support

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schema-object

API version: 1.0.0
Contact: a-team@goarmy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polymorphism

import (
	"encoding/json"
	"fmt"
)

// checks if the Denmark type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Denmark{}

// Denmark struct for Denmark
type Denmark struct {
	ListingId int32 `json:"listing_id"`
	RegulatoryBody string `json:"regulatory_body"`
	Categorization DenmarkCategorization `json:"categorization"`
	AdditionalProperties map[string]interface{}
}

type _Denmark Denmark

// NewDenmark instantiates a new Denmark object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDenmark(listingId int32, regulatoryBody string, categorization DenmarkCategorization) *Denmark {
	this := Denmark{}
	this.ListingId = listingId
	this.RegulatoryBody = regulatoryBody
	this.Categorization = categorization
	return &this
}

// NewDenmarkWithDefaults instantiates a new Denmark object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDenmarkWithDefaults() *Denmark {
	this := Denmark{}
	return &this
}

// GetListingId returns the ListingId field value
func (o *Denmark) GetListingId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ListingId
}

// GetListingIdOk returns a tuple with the ListingId field value
// and a boolean to check if the value has been set.
func (o *Denmark) GetListingIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ListingId, true
}

// SetListingId sets field value
func (o *Denmark) SetListingId(v int32) {
	o.ListingId = v
}

// GetRegulatoryBody returns the RegulatoryBody field value
func (o *Denmark) GetRegulatoryBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegulatoryBody
}

// GetRegulatoryBodyOk returns a tuple with the RegulatoryBody field value
// and a boolean to check if the value has been set.
func (o *Denmark) GetRegulatoryBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegulatoryBody, true
}

// SetRegulatoryBody sets field value
func (o *Denmark) SetRegulatoryBody(v string) {
	o.RegulatoryBody = v
}

// GetCategorization returns the Categorization field value
func (o *Denmark) GetCategorization() DenmarkCategorization {
	if o == nil {
		var ret DenmarkCategorization
		return ret
	}

	return o.Categorization
}

// GetCategorizationOk returns a tuple with the Categorization field value
// and a boolean to check if the value has been set.
func (o *Denmark) GetCategorizationOk() (*DenmarkCategorization, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Categorization, true
}

// SetCategorization sets field value
func (o *Denmark) SetCategorization(v DenmarkCategorization) {
	o.Categorization = v
}

func (o Denmark) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Denmark) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["listing_id"] = o.ListingId
	toSerialize["regulatory_body"] = o.RegulatoryBody
	toSerialize["categorization"] = o.Categorization

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Denmark) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"listing_id",
		"regulatory_body",
		"categorization",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDenmark := _Denmark{}

	err = json.Unmarshal(data, &varDenmark)

	if err != nil {
		return err
	}

	*o = Denmark(varDenmark)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "listing_id")
		delete(additionalProperties, "regulatory_body")
		delete(additionalProperties, "categorization")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDenmark struct {
	value *Denmark
	isSet bool
}

func (v NullableDenmark) Get() *Denmark {
	return v.value
}

func (v *NullableDenmark) Set(val *Denmark) {
	v.value = val
	v.isSet = true
}

func (v NullableDenmark) IsSet() bool {
	return v.isSet
}

func (v *NullableDenmark) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDenmark(val *Denmark) *NullableDenmark {
	return &NullableDenmark{value: val, isSet: true}
}

func (v NullableDenmark) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDenmark) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


