/*
Polymorphism support

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schema-object

API version: 1.0.0
Contact: a-team@goarmy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polymorphism

import (
	"encoding/json"
)

// checks if the AnythingAllOfObjectRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnythingAllOfObjectRequest{}

// AnythingAllOfObjectRequest struct for AnythingAllOfObjectRequest
type AnythingAllOfObjectRequest struct {
	A *string `json:"a,omitempty"`
	B *string `json:"b,omitempty"`
	C *string `json:"c,omitempty"`
	D *string `json:"d,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AnythingAllOfObjectRequest AnythingAllOfObjectRequest

// NewAnythingAllOfObjectRequest instantiates a new AnythingAllOfObjectRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnythingAllOfObjectRequest() *AnythingAllOfObjectRequest {
	this := AnythingAllOfObjectRequest{}
	return &this
}

// NewAnythingAllOfObjectRequestWithDefaults instantiates a new AnythingAllOfObjectRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnythingAllOfObjectRequestWithDefaults() *AnythingAllOfObjectRequest {
	this := AnythingAllOfObjectRequest{}
	return &this
}

// GetA returns the A field value if set, zero value otherwise.
func (o *AnythingAllOfObjectRequest) GetA() string {
	if o == nil || IsNil(o.A) {
		var ret string
		return ret
	}
	return *o.A
}

// GetAOk returns a tuple with the A field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnythingAllOfObjectRequest) GetAOk() (*string, bool) {
	if o == nil || IsNil(o.A) {
		return nil, false
	}
	return o.A, true
}

// HasA returns a boolean if a field has been set.
func (o *AnythingAllOfObjectRequest) HasA() bool {
	if o != nil && !IsNil(o.A) {
		return true
	}

	return false
}

// SetA gets a reference to the given string and assigns it to the A field.
func (o *AnythingAllOfObjectRequest) SetA(v string) {
	o.A = &v
}

// GetB returns the B field value if set, zero value otherwise.
func (o *AnythingAllOfObjectRequest) GetB() string {
	if o == nil || IsNil(o.B) {
		var ret string
		return ret
	}
	return *o.B
}

// GetBOk returns a tuple with the B field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnythingAllOfObjectRequest) GetBOk() (*string, bool) {
	if o == nil || IsNil(o.B) {
		return nil, false
	}
	return o.B, true
}

// HasB returns a boolean if a field has been set.
func (o *AnythingAllOfObjectRequest) HasB() bool {
	if o != nil && !IsNil(o.B) {
		return true
	}

	return false
}

// SetB gets a reference to the given string and assigns it to the B field.
func (o *AnythingAllOfObjectRequest) SetB(v string) {
	o.B = &v
}

// GetC returns the C field value if set, zero value otherwise.
func (o *AnythingAllOfObjectRequest) GetC() string {
	if o == nil || IsNil(o.C) {
		var ret string
		return ret
	}
	return *o.C
}

// GetCOk returns a tuple with the C field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnythingAllOfObjectRequest) GetCOk() (*string, bool) {
	if o == nil || IsNil(o.C) {
		return nil, false
	}
	return o.C, true
}

// HasC returns a boolean if a field has been set.
func (o *AnythingAllOfObjectRequest) HasC() bool {
	if o != nil && !IsNil(o.C) {
		return true
	}

	return false
}

// SetC gets a reference to the given string and assigns it to the C field.
func (o *AnythingAllOfObjectRequest) SetC(v string) {
	o.C = &v
}

// GetD returns the D field value if set, zero value otherwise.
func (o *AnythingAllOfObjectRequest) GetD() string {
	if o == nil || IsNil(o.D) {
		var ret string
		return ret
	}
	return *o.D
}

// GetDOk returns a tuple with the D field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnythingAllOfObjectRequest) GetDOk() (*string, bool) {
	if o == nil || IsNil(o.D) {
		return nil, false
	}
	return o.D, true
}

// HasD returns a boolean if a field has been set.
func (o *AnythingAllOfObjectRequest) HasD() bool {
	if o != nil && !IsNil(o.D) {
		return true
	}

	return false
}

// SetD gets a reference to the given string and assigns it to the D field.
func (o *AnythingAllOfObjectRequest) SetD(v string) {
	o.D = &v
}

func (o AnythingAllOfObjectRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnythingAllOfObjectRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.A) {
		toSerialize["a"] = o.A
	}
	if !IsNil(o.B) {
		toSerialize["b"] = o.B
	}
	if !IsNil(o.C) {
		toSerialize["c"] = o.C
	}
	if !IsNil(o.D) {
		toSerialize["d"] = o.D
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AnythingAllOfObjectRequest) UnmarshalJSON(data []byte) (err error) {
	varAnythingAllOfObjectRequest := _AnythingAllOfObjectRequest{}

	err = json.Unmarshal(data, &varAnythingAllOfObjectRequest)

	if err != nil {
		return err
	}

	*o = AnythingAllOfObjectRequest(varAnythingAllOfObjectRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "a")
		delete(additionalProperties, "b")
		delete(additionalProperties, "c")
		delete(additionalProperties, "d")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAnythingAllOfObjectRequest struct {
	value *AnythingAllOfObjectRequest
	isSet bool
}

func (v NullableAnythingAllOfObjectRequest) Get() *AnythingAllOfObjectRequest {
	return v.value
}

func (v *NullableAnythingAllOfObjectRequest) Set(val *AnythingAllOfObjectRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAnythingAllOfObjectRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAnythingAllOfObjectRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnythingAllOfObjectRequest(val *AnythingAllOfObjectRequest) *NullableAnythingAllOfObjectRequest {
	return &NullableAnythingAllOfObjectRequest{value: val, isSet: true}
}

func (v NullableAnythingAllOfObjectRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnythingAllOfObjectRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


