/*
Polymorphism support

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schema-object

API version: 1.0.0
Contact: a-team@goarmy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polymorphism

import (
	"encoding/json"
	"fmt"
)

// checks if the AndaluciaRegistration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AndaluciaRegistration{}

// AndaluciaRegistration struct for AndaluciaRegistration
type AndaluciaRegistration struct {
	PermitNumber string `json:"permit_number"`
	RegistrationOwnership string `json:"registration_ownership"`
	Email string `json:"email"`
	FullName string `json:"full_name"`
	IdentificationNumber string `json:"identification_number"`
	AdditionalProperties map[string]interface{}
}

type _AndaluciaRegistration AndaluciaRegistration

// NewAndaluciaRegistration instantiates a new AndaluciaRegistration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAndaluciaRegistration(permitNumber string, registrationOwnership string, email string, fullName string, identificationNumber string) *AndaluciaRegistration {
	this := AndaluciaRegistration{}
	this.PermitNumber = permitNumber
	this.RegistrationOwnership = registrationOwnership
	this.Email = email
	this.FullName = fullName
	this.IdentificationNumber = identificationNumber
	return &this
}

// NewAndaluciaRegistrationWithDefaults instantiates a new AndaluciaRegistration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAndaluciaRegistrationWithDefaults() *AndaluciaRegistration {
	this := AndaluciaRegistration{}
	return &this
}

// GetPermitNumber returns the PermitNumber field value
func (o *AndaluciaRegistration) GetPermitNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PermitNumber
}

// GetPermitNumberOk returns a tuple with the PermitNumber field value
// and a boolean to check if the value has been set.
func (o *AndaluciaRegistration) GetPermitNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PermitNumber, true
}

// SetPermitNumber sets field value
func (o *AndaluciaRegistration) SetPermitNumber(v string) {
	o.PermitNumber = v
}

// GetRegistrationOwnership returns the RegistrationOwnership field value
func (o *AndaluciaRegistration) GetRegistrationOwnership() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegistrationOwnership
}

// GetRegistrationOwnershipOk returns a tuple with the RegistrationOwnership field value
// and a boolean to check if the value has been set.
func (o *AndaluciaRegistration) GetRegistrationOwnershipOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegistrationOwnership, true
}

// SetRegistrationOwnership sets field value
func (o *AndaluciaRegistration) SetRegistrationOwnership(v string) {
	o.RegistrationOwnership = v
}

// GetEmail returns the Email field value
func (o *AndaluciaRegistration) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *AndaluciaRegistration) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *AndaluciaRegistration) SetEmail(v string) {
	o.Email = v
}

// GetFullName returns the FullName field value
func (o *AndaluciaRegistration) GetFullName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value
// and a boolean to check if the value has been set.
func (o *AndaluciaRegistration) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FullName, true
}

// SetFullName sets field value
func (o *AndaluciaRegistration) SetFullName(v string) {
	o.FullName = v
}

// GetIdentificationNumber returns the IdentificationNumber field value
func (o *AndaluciaRegistration) GetIdentificationNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdentificationNumber
}

// GetIdentificationNumberOk returns a tuple with the IdentificationNumber field value
// and a boolean to check if the value has been set.
func (o *AndaluciaRegistration) GetIdentificationNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdentificationNumber, true
}

// SetIdentificationNumber sets field value
func (o *AndaluciaRegistration) SetIdentificationNumber(v string) {
	o.IdentificationNumber = v
}

func (o AndaluciaRegistration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AndaluciaRegistration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["permit_number"] = o.PermitNumber
	toSerialize["registration_ownership"] = o.RegistrationOwnership
	toSerialize["email"] = o.Email
	toSerialize["full_name"] = o.FullName
	toSerialize["identification_number"] = o.IdentificationNumber

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AndaluciaRegistration) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"permit_number",
		"registration_ownership",
		"email",
		"full_name",
		"identification_number",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAndaluciaRegistration := _AndaluciaRegistration{}

	err = json.Unmarshal(data, &varAndaluciaRegistration)

	if err != nil {
		return err
	}

	*o = AndaluciaRegistration(varAndaluciaRegistration)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "permit_number")
		delete(additionalProperties, "registration_ownership")
		delete(additionalProperties, "email")
		delete(additionalProperties, "full_name")
		delete(additionalProperties, "identification_number")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAndaluciaRegistration struct {
	value *AndaluciaRegistration
	isSet bool
}

func (v NullableAndaluciaRegistration) Get() *AndaluciaRegistration {
	return v.value
}

func (v *NullableAndaluciaRegistration) Set(val *AndaluciaRegistration) {
	v.value = val
	v.isSet = true
}

func (v NullableAndaluciaRegistration) IsSet() bool {
	return v.isSet
}

func (v *NullableAndaluciaRegistration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAndaluciaRegistration(val *AndaluciaRegistration) *NullableAndaluciaRegistration {
	return &NullableAndaluciaRegistration{value: val, isSet: true}
}

func (v NullableAndaluciaRegistration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAndaluciaRegistration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


