/*
Polymorphism support

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schema-object

API version: 1.0.0
Contact: a-team@goarmy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polymorphism

import (
	"encoding/json"
	"fmt"
)

// AnythingOneOfPrimitiveRequest - struct for AnythingOneOfPrimitiveRequest
type AnythingOneOfPrimitiveRequest struct {
	Int32 *int32
	String *string
}

// int32AsAnythingOneOfPrimitiveRequest is a convenience function that returns int32 wrapped in AnythingOneOfPrimitiveRequest
func Int32AsAnythingOneOfPrimitiveRequest(v *int32) AnythingOneOfPrimitiveRequest {
	return AnythingOneOfPrimitiveRequest{
		Int32: v,
	}
}

// stringAsAnythingOneOfPrimitiveRequest is a convenience function that returns string wrapped in AnythingOneOfPrimitiveRequest
func StringAsAnythingOneOfPrimitiveRequest(v *string) AnythingOneOfPrimitiveRequest {
	return AnythingOneOfPrimitiveRequest{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *AnythingOneOfPrimitiveRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			match++
		}
	} else {
		dst.Int32 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			match++
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Int32 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(AnythingOneOfPrimitiveRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(AnythingOneOfPrimitiveRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src AnythingOneOfPrimitiveRequest) MarshalJSON() ([]byte, error) {
	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *AnythingOneOfPrimitiveRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Int32 != nil {
		return obj.Int32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableAnythingOneOfPrimitiveRequest struct {
	value *AnythingOneOfPrimitiveRequest
	isSet bool
}

func (v NullableAnythingOneOfPrimitiveRequest) Get() *AnythingOneOfPrimitiveRequest {
	return v.value
}

func (v *NullableAnythingOneOfPrimitiveRequest) Set(val *AnythingOneOfPrimitiveRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAnythingOneOfPrimitiveRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAnythingOneOfPrimitiveRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnythingOneOfPrimitiveRequest(val *AnythingOneOfPrimitiveRequest) *NullableAnythingOneOfPrimitiveRequest {
	return &NullableAnythingOneOfPrimitiveRequest{value: val, isSet: true}
}

func (v NullableAnythingOneOfPrimitiveRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnythingOneOfPrimitiveRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


