/*
Polymorphism support

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schema-object

API version: 1.0.0
Contact: a-team@goarmy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polymorphism

import (
	"encoding/json"
)

// checks if the AnythingNestedOneOfRefRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnythingNestedOneOfRefRequest{}

// AnythingNestedOneOfRefRequest struct for AnythingNestedOneOfRefRequest
type AnythingNestedOneOfRefRequest struct {
	Config *AnythingNestedOneOfRefRequestConfig `json:"config,omitempty"`
}

// NewAnythingNestedOneOfRefRequest instantiates a new AnythingNestedOneOfRefRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnythingNestedOneOfRefRequest() *AnythingNestedOneOfRefRequest {
	this := AnythingNestedOneOfRefRequest{}
	return &this
}

// NewAnythingNestedOneOfRefRequestWithDefaults instantiates a new AnythingNestedOneOfRefRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnythingNestedOneOfRefRequestWithDefaults() *AnythingNestedOneOfRefRequest {
	this := AnythingNestedOneOfRefRequest{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *AnythingNestedOneOfRefRequest) GetConfig() AnythingNestedOneOfRefRequestConfig {
	if o == nil || IsNil(o.Config) {
		var ret AnythingNestedOneOfRefRequestConfig
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnythingNestedOneOfRefRequest) GetConfigOk() (*AnythingNestedOneOfRefRequestConfig, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *AnythingNestedOneOfRefRequest) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given AnythingNestedOneOfRefRequestConfig and assigns it to the Config field.
func (o *AnythingNestedOneOfRefRequest) SetConfig(v AnythingNestedOneOfRefRequestConfig) {
	o.Config = &v
}

func (o AnythingNestedOneOfRefRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnythingNestedOneOfRefRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	return toSerialize, nil
}

type NullableAnythingNestedOneOfRefRequest struct {
	value *AnythingNestedOneOfRefRequest
	isSet bool
}

func (v NullableAnythingNestedOneOfRefRequest) Get() *AnythingNestedOneOfRefRequest {
	return v.value
}

func (v *NullableAnythingNestedOneOfRefRequest) Set(val *AnythingNestedOneOfRefRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAnythingNestedOneOfRefRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAnythingNestedOneOfRefRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnythingNestedOneOfRefRequest(val *AnythingNestedOneOfRefRequest) *NullableAnythingNestedOneOfRefRequest {
	return &NullableAnythingNestedOneOfRefRequest{value: val, isSet: true}
}

func (v NullableAnythingNestedOneOfRefRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnythingNestedOneOfRefRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


