/*
Polymorphism support

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schema-object

API version: 1.0.0
Contact: a-team@goarmy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polymorphism

import (
	"encoding/json"
	"fmt"
)

// checks if the Chicago type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Chicago{}

// Chicago struct for Chicago
type Chicago struct {
	ListingId int32 `json:"listing_id"`
	RegulatoryBody string `json:"regulatory_body"`
	Registration ChicagoRegistration `json:"registration"`
	AdditionalProperties map[string]interface{}
}

type _Chicago Chicago

// NewChicago instantiates a new Chicago object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChicago(listingId int32, regulatoryBody string, registration ChicagoRegistration) *Chicago {
	this := Chicago{}
	this.ListingId = listingId
	this.RegulatoryBody = regulatoryBody
	this.Registration = registration
	return &this
}

// NewChicagoWithDefaults instantiates a new Chicago object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChicagoWithDefaults() *Chicago {
	this := Chicago{}
	return &this
}

// GetListingId returns the ListingId field value
func (o *Chicago) GetListingId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ListingId
}

// GetListingIdOk returns a tuple with the ListingId field value
// and a boolean to check if the value has been set.
func (o *Chicago) GetListingIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ListingId, true
}

// SetListingId sets field value
func (o *Chicago) SetListingId(v int32) {
	o.ListingId = v
}

// GetRegulatoryBody returns the RegulatoryBody field value
func (o *Chicago) GetRegulatoryBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegulatoryBody
}

// GetRegulatoryBodyOk returns a tuple with the RegulatoryBody field value
// and a boolean to check if the value has been set.
func (o *Chicago) GetRegulatoryBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegulatoryBody, true
}

// SetRegulatoryBody sets field value
func (o *Chicago) SetRegulatoryBody(v string) {
	o.RegulatoryBody = v
}

// GetRegistration returns the Registration field value
func (o *Chicago) GetRegistration() ChicagoRegistration {
	if o == nil {
		var ret ChicagoRegistration
		return ret
	}

	return o.Registration
}

// GetRegistrationOk returns a tuple with the Registration field value
// and a boolean to check if the value has been set.
func (o *Chicago) GetRegistrationOk() (*ChicagoRegistration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Registration, true
}

// SetRegistration sets field value
func (o *Chicago) SetRegistration(v ChicagoRegistration) {
	o.Registration = v
}

func (o Chicago) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Chicago) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["listing_id"] = o.ListingId
	toSerialize["regulatory_body"] = o.RegulatoryBody
	toSerialize["registration"] = o.Registration

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Chicago) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"listing_id",
		"regulatory_body",
		"registration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChicago := _Chicago{}

	err = json.Unmarshal(data, &varChicago)

	if err != nil {
		return err
	}

	*o = Chicago(varChicago)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "listing_id")
		delete(additionalProperties, "regulatory_body")
		delete(additionalProperties, "registration")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChicago struct {
	value *Chicago
	isSet bool
}

func (v NullableChicago) Get() *Chicago {
	return v.value
}

func (v *NullableChicago) Set(val *Chicago) {
	v.value = val
	v.isSet = true
}

func (v NullableChicago) IsSet() bool {
	return v.isSet
}

func (v *NullableChicago) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChicago(val *Chicago) *NullableChicago {
	return &NullableChicago{value: val, isSet: true}
}

func (v NullableChicago) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChicago) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


