/*
Polymorphism support

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schema-object

API version: 1.0.0
Contact: a-team@goarmy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polymorphism

import (
	"encoding/json"
)

// checks if the AnythingNestedOneOfObjectRefRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnythingNestedOneOfObjectRefRequest{}

// AnythingNestedOneOfObjectRefRequest struct for AnythingNestedOneOfObjectRefRequest
type AnythingNestedOneOfObjectRefRequest struct {
	Config *AnythingOneOfObjectRefRequest `json:"config,omitempty"`
}

// NewAnythingNestedOneOfObjectRefRequest instantiates a new AnythingNestedOneOfObjectRefRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnythingNestedOneOfObjectRefRequest() *AnythingNestedOneOfObjectRefRequest {
	this := AnythingNestedOneOfObjectRefRequest{}
	return &this
}

// NewAnythingNestedOneOfObjectRefRequestWithDefaults instantiates a new AnythingNestedOneOfObjectRefRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnythingNestedOneOfObjectRefRequestWithDefaults() *AnythingNestedOneOfObjectRefRequest {
	this := AnythingNestedOneOfObjectRefRequest{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *AnythingNestedOneOfObjectRefRequest) GetConfig() AnythingOneOfObjectRefRequest {
	if o == nil || IsNil(o.Config) {
		var ret AnythingOneOfObjectRefRequest
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnythingNestedOneOfObjectRefRequest) GetConfigOk() (*AnythingOneOfObjectRefRequest, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *AnythingNestedOneOfObjectRefRequest) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given AnythingOneOfObjectRefRequest and assigns it to the Config field.
func (o *AnythingNestedOneOfObjectRefRequest) SetConfig(v AnythingOneOfObjectRefRequest) {
	o.Config = &v
}

func (o AnythingNestedOneOfObjectRefRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnythingNestedOneOfObjectRefRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	return toSerialize, nil
}

type NullableAnythingNestedOneOfObjectRefRequest struct {
	value *AnythingNestedOneOfObjectRefRequest
	isSet bool
}

func (v NullableAnythingNestedOneOfObjectRefRequest) Get() *AnythingNestedOneOfObjectRefRequest {
	return v.value
}

func (v *NullableAnythingNestedOneOfObjectRefRequest) Set(val *AnythingNestedOneOfObjectRefRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAnythingNestedOneOfObjectRefRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAnythingNestedOneOfObjectRefRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnythingNestedOneOfObjectRefRequest(val *AnythingNestedOneOfObjectRefRequest) *NullableAnythingNestedOneOfObjectRefRequest {
	return &NullableAnythingNestedOneOfObjectRefRequest{value: val, isSet: true}
}

func (v NullableAnythingNestedOneOfObjectRefRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnythingNestedOneOfObjectRefRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


