openapi: "3.0.0"
tags:
  - name: post_cards
info:
  contact:
    name: A-Team
    email: a-team@goarmy.com
    url: goarmy.com/apis/support
  version: 1.0.0
  title: Card
  description: An example exploring the use of oneOf with properties
servers:
  - url: http://localhost/api
paths:
  '/cards':
    post:
      operationId: post_cards
      tags: 
        - post_cards
      description: Create cards
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createCards'
      responses:
        '201':
          description: Created
        'default':
            description: "unexpected error"
components:
  schemas:
    createCards:
      type: object
      properties:
        cards:
          description: Schema for the cards
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/PlayingCard'
              - $ref: '#/components/schemas/BaseballCard'
    PlayingCard:
      type: object
      description: Playing Card
      required:
        - rank
        - suite
      properties:
        rank:
          type: string
          example: 'K'
        suite:
          type: string
          example: 'clubs'
    BaseballCard:
      type: object
      description: Baseball Card
      required:
        - rank
        - suite
      properties:
        player:
          type: string
          example: 'Mickey Mantle'
        team:
          type: string
          example: 'Yankees'
