// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/ogen-go/ogen/validate"
)

func decodeAnythingAllOfObjectResponse(resp *http.Response) (res *AnythingAllOfObjectOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &AnythingAllOfObjectOK{}, nil
	}
	return res, validate.UnexpectedStatusCode(resp.StatusCode)
}

func decodeAnythingAnyOfPrimitiveResponse(resp *http.Response) (res *AnythingAnyOfPrimitiveOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &AnythingAnyOfPrimitiveOK{}, nil
	}
	return res, validate.UnexpectedStatusCode(resp.StatusCode)
}

func decodeAnythingNestedOneOfObjectRefResponse(resp *http.Response) (res *AnythingNestedOneOfObjectRefOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &AnythingNestedOneOfObjectRefOK{}, nil
	}
	return res, validate.UnexpectedStatusCode(resp.StatusCode)
}

func decodeAnythingOneOfObjectResponse(resp *http.Response) (res *AnythingOneOfObjectOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &AnythingOneOfObjectOK{}, nil
	}
	return res, validate.UnexpectedStatusCode(resp.StatusCode)
}

func decodeAnythingOneOfObjectRefResponse(resp *http.Response) (res *AnythingOneOfObjectRefOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &AnythingOneOfObjectRefOK{}, nil
	}
	return res, validate.UnexpectedStatusCode(resp.StatusCode)
}

func decodeAnythingOneOfPrimitiveResponse(resp *http.Response) (res *AnythingOneOfPrimitiveOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &AnythingOneOfPrimitiveOK{}, nil
	}
	return res, validate.UnexpectedStatusCode(resp.StatusCode)
}

func decodeGetPetsResponse(resp *http.Response) (res *GetPetsOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &GetPetsOK{}, nil
	}
	return res, validate.UnexpectedStatusCode(resp.StatusCode)
}
