// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AnythingAllOfObject implements anything-all-of-object operation.
	//
	// AllOf with listed objects.
	//
	// POST /anything/all-of-object
	AnythingAllOfObject(ctx context.Context, req OptAnythingAllOfObjectReq) error
	// AnythingAnyOfPrimitive implements anything-any-of-primitive operation.
	//
	// Description.
	//
	// POST /anything/any-of-primitive
	AnythingAnyOfPrimitive(ctx context.Context, req OptAnythingAnyOfPrimitiveReq) error
	// AnythingNestedOneOfObjectRef implements anything-nested-one-of-object-ref operation.
	//
	// Description.
	//
	// POST /anything/nested-one-of-object-ref
	AnythingNestedOneOfObjectRef(ctx context.Context, req OptAnythingNestedOneOfObjectRefReq) error
	// AnythingOneOfObject implements anything-one-of-object operation.
	//
	// Description.
	//
	// POST /anything/one-of-object
	AnythingOneOfObject(ctx context.Context, req OptAnythingOneOfObjectReq) error
	// AnythingOneOfObjectRef implements anything-one-of-object-ref operation.
	//
	// Description.
	//
	// POST /anything/one-of-object-ref
	AnythingOneOfObjectRef(ctx context.Context, req OptAnythingOneOfObjectRefReq) error
	// AnythingOneOfPrimitive implements anything-one-of-primitive operation.
	//
	// Description.
	//
	// POST /anything/one-of-primitive
	AnythingOneOfPrimitive(ctx context.Context, req OptAnythingOneOfPrimitiveReq) error
	// GetPets implements get_pets operation.
	//
	// OneOf request with a nested allOf.
	//
	// PATCH /pets
	GetPets(ctx context.Context, req OptGetPetsReq) error
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
