// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AnythingAllOfObject implements anything-all-of-object operation.
//
// AllOf with listed objects.
//
// POST /anything/all-of-object
func (UnimplementedHandler) AnythingAllOfObject(ctx context.Context, req OptAnythingAllOfObjectReq) error {
	return ht.ErrNotImplemented
}

// AnythingAnyOfPrimitive implements anything-any-of-primitive operation.
//
// Description.
//
// POST /anything/any-of-primitive
func (UnimplementedHandler) AnythingAnyOfPrimitive(ctx context.Context, req OptAnythingAnyOfPrimitiveReq) error {
	return ht.ErrNotImplemented
}

// AnythingNestedOneOfObjectRef implements anything-nested-one-of-object-ref operation.
//
// Description.
//
// POST /anything/nested-one-of-object-ref
func (UnimplementedHandler) AnythingNestedOneOfObjectRef(ctx context.Context, req OptAnythingNestedOneOfObjectRefReq) error {
	return ht.ErrNotImplemented
}

// AnythingOneOfObject implements anything-one-of-object operation.
//
// Description.
//
// POST /anything/one-of-object
func (UnimplementedHandler) AnythingOneOfObject(ctx context.Context, req OptAnythingOneOfObjectReq) error {
	return ht.ErrNotImplemented
}

// AnythingOneOfObjectRef implements anything-one-of-object-ref operation.
//
// Description.
//
// POST /anything/one-of-object-ref
func (UnimplementedHandler) AnythingOneOfObjectRef(ctx context.Context, req OptAnythingOneOfObjectRefReq) error {
	return ht.ErrNotImplemented
}

// AnythingOneOfPrimitive implements anything-one-of-primitive operation.
//
// Description.
//
// POST /anything/one-of-primitive
func (UnimplementedHandler) AnythingOneOfPrimitive(ctx context.Context, req OptAnythingOneOfPrimitiveReq) error {
	return ht.ErrNotImplemented
}

// GetPets implements get_pets operation.
//
// OneOf request with a nested allOf.
//
// PATCH /pets
func (UnimplementedHandler) GetPets(ctx context.Context, req OptGetPetsReq) error {
	return ht.ErrNotImplemented
}
